### ISSUE TITLE
Reload packer package compilation on VimEnter

### ISSUE THREAD

**Issue by sinetoami** [gbrlsnchs/dotfiles#1]
First of all, thanks for maintaining your dotfiles very understandable. It's helping me a lot.

So, I've noticed that Packer hasn't a hot reload or some kind of auto compilation. I've to do `:PackerSync` ou `:PackerCompile`, sometimes even remove the `plugin/packer_compiled.vim` file, to be able to see configs modifications. So, is it the purpose of packer.nvim?

Thanks in advance.

**Comment by gbrlsnchs** [comment]
Hi @sinetoami, I'm glad this repo is helping you with your dotfiles!

Packer compiles everything in order to optimize startup time by lazily loading plugins. So after you change something in plugin configurations, yeah, you need to compile plugins again. It's a trade-off for faster startup times.

Note that before running `PackerCompile`, you have to reload your Lua module, otherwise `PackerCompile` will still compile the old configuration. What I do is quit Neovim, enter on in again, run `PackerCompile` and then re-enter to have changes applied (quit > re-enter > `PackerCompile` > quit > re-enter).

I know this is NOT an ideal workflow, but it's because Lua modules are cached, so you can't simply "source" them again using `require`, hence why I quit and re-enter Neovim one first time before compiling plugins. In the future, I intend to use [plenary.nvim](https://github.com/nvim-lua/plenary.nvim), which has a utility to truly reload Lua modules, so I don't have to quit Neovim to compile plugins.

**Comment by sinetoami** [comment]
Got it! I do the same steps, and add one more step (remove `packer_compiled.vim`) when necessary. But I can understand the purpose now. Thanks for your explanation. Helps a lot.

About to build a plugin to reload Lua modules it's quite nice! I'll wait for that.
Thanks again!
